@echo off
echo Creating shadcn components...

REM Create directory structure
if not exist "src\components\ui" mkdir src\components\ui

REM Use PowerShell to create files (avoids batch line length limits)
powershell -Command "$content = @'^
import * as React from \"react\"`nimport { Command as CommandPrimitive } from \"cmdk\"`nimport { cn } from \"../../lib/utils\"`n`nconst Command = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<CommandPrimitive`n    ref={ref}`n    className={cn(`n      \"flex h-full w-full flex-col overflow-hidden rounded-md bg-popover text-popover-foreground\",`n      className`n    )}`n    {...props}`n  /^>`n))`nCommand.displayName = CommandPrimitive.displayName`n`nconst CommandInput = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<div className=\"flex items-center border-b px-3\"^>`n    ^<CommandPrimitive.Input`n      ref={ref}`n      className={cn(`n        \"flex h-11 w-full rounded-md bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50\",`n        className`n      )}`n      {...props}`n    /^>`n  ^</div^>`n))`nCommandInput.displayName = CommandPrimitive.Input.displayName`n`nconst CommandList = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<CommandPrimitive.List`n    ref={ref}`n    className={cn(\"max-h-[300px] overflow-y-auto overflow-x-hidden\", className)}`n    {...props}`n  /^>`n))`nCommandList.displayName = CommandPrimitive.List.displayName`n`nconst CommandEmpty = React.forwardRef((props, ref) =^> (`n  ^<CommandPrimitive.Empty ref={ref} className=\"py-6 text-center text-sm\" {...props} /^>`n))`nCommandEmpty.displayName = CommandPrimitive.Empty.displayName`n`nconst CommandGroup = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<CommandPrimitive.Group`n    ref={ref}`n    className={cn(`n      \"overflow-hidden p-1 text-foreground [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground\",`n      className`n    )}`n    {...props}`n  /^>`n))`nCommandGroup.displayName = CommandPrimitive.Group.displayName`n`nconst CommandItem = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<CommandPrimitive.Item`n    ref={ref}`n    className={cn(`n      \"relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50\",`n      className`n    )}`n    {...props}`n  /^>`n))`nCommandItem.displayName = CommandPrimitive.Item.displayName`n`nexport { Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem }`n'^@; Set-Content -Path 'src\components\ui\command.jsx' -Value $content"

powershell -Command "$content = @'^
import * as React from \"react\"`nimport { cn } from \"../../lib/utils\"`n`nconst Button = React.forwardRef(({ className, variant = \"default\", size = \"default\", ...props }, ref) =^> {`n  return (`n    ^<button`n      className={cn(`n        \"inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50\",`n        {`n          \"bg-primary text-primary-foreground hover:bg-primary/90\": variant === \"default\",`n          \"bg-destructive text-destructive-foreground hover:bg-destructive/90\": variant === \"destructive\",`n          \"border border-input bg-background hover:bg-accent hover:text-accent-foreground\": variant === \"outline\",`n          \"bg-secondary text-secondary-foreground hover:bg-secondary/80\": variant === \"secondary\",`n          \"hover:bg-accent hover:text-accent-foreground\": variant === \"ghost\",`n          \"text-primary underline-offset-4 hover:underline\": variant === \"link\",`n        },`n        {`n          \"h-10 px-4 py-2\": size === \"default\",`n          \"h-9 rounded-md px-3\": size === \"sm\",`n          \"h-11 rounded-md px-8\": size === \"lg\",`n          \"h-10 w-10\": size === \"icon\",`n        },`n        className`n      )}`n      ref={ref}`n      {...props}`n    /^>`n  )`n})`n`nButton.displayName = \"Button\"`n`nexport { Button }`n'^@; Set-Content -Path 'src\components\ui\button.jsx' -Value $content"

powershell -Command "$content = @'^
import * as React from \"react\"`nimport { cn } from \"../../lib/utils\"`n`nfunction Badge({ className, variant = \"default\", ...props }) {`n  return (`n    ^<div`n      className={cn(`n        \"inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2\",`n        {`n          \"border-transparent bg-primary text-primary-foreground hover:bg-primary/80\": variant === \"default\",`n          \"border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80\": variant === \"secondary\",`n          \"border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80\": variant === \"destructive\",`n          \"text-foreground\": variant === \"outline\",`n        },`n        className`n      )}`n      {...props}`n    /^>`n  )`n}`n`nexport { Badge }`n'^@; Set-Content -Path 'src\components\ui\badge.jsx' -Value $content"

powershell -Command "$content = @'^
import * as React from \"react\"`nimport { cn } from \"../../lib/utils\"`n`nconst Input = React.forwardRef(({ className, type, ...props }, ref) =^> {`n  return (`n    ^<input`n      type={type}`n      className={cn(`n        \"flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50\",`n        className`n      )}`n      ref={ref}`n      {...props}`n    /^>`n  )`n})`n`nInput.displayName = \"Input\"`n`nexport { Input }`n'^@; Set-Content -Path 'src\components\ui\input.jsx' -Value $content"

powershell -Command "$content = @'^
import * as React from \"react\"`nimport { cn } from \"../../lib/utils\"`n`nconst Card = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<div`n    ref={ref}`n    className={cn(`n      \"rounded-lg border bg-card text-card-foreground shadow-sm\",`n      className`n    )}`n    {...props}`n  /^>`n))`nCard.displayName = \"Card\"`n`nconst CardHeader = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<div`n    ref={ref}`n    className={cn(\"flex flex-col space-y-1.5 p-6\", className)}`n    {...props}`n  /^>`n))`nCardHeader.displayName = \"CardHeader\"`n`nconst CardTitle = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<h3`n    ref={ref}`n    className={cn(`n      \"text-2xl font-semibold leading-none tracking-tight\",`n      className`n    )}`n    {...props}`n  /^>`n))`nCardTitle.displayName = \"CardTitle\"`n`nconst CardDescription = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<p`n    ref={ref}`n    className={cn(\"text-sm text-muted-foreground\", className)}`n    {...props}`n  /^>`n))`nCardDescription.displayName = \"CardDescription\"`n`nconst CardContent = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<div ref={ref} className={cn(\"p-6 pt-0\", className)} {...props} /^>`n))`nCardContent.displayName = \"CardContent\"`n`nconst CardFooter = React.forwardRef(({ className, ...props }, ref) =^> (`n  ^<div`n    ref={ref}`n    className={cn(\"flex items-center p-6 pt-0\", className)}`n    {...props}`n  /^>`n))`nCardFooter.displayName = \"CardFooter\"`n`nexport { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent }`n'^@; Set-Content -Path 'src\components\ui\card.jsx' -Value $content"

echo.
echo ✓ Created command.jsx
echo ✓ Created button.jsx
echo ✓ Created badge.jsx
echo ✓ Created input.jsx
echo ✓ Created card.jsx
echo.
echo All components created successfully in src\components\ui\
pause
