const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('panelAPI', {
  getData: () => ipcRenderer.invoke('get-data'),
  clarifyIntent: (text) => ipcRenderer.invoke('clarify-intent', text),
  generateTasks: (intentText) => ipcRenderer.invoke('generate-tasks', intentText),
  addIntent: (intent) => ipcRenderer.invoke('add-intent', intent),
  deleteIntent: (id) => ipcRenderer.invoke('delete-intent', id),
  addFile: (file) => ipcRenderer.invoke('add-file', file),
  removeFile: (id) => ipcRenderer.invoke('remove-file', id),
  openFile: (path) => ipcRenderer.invoke('open-file', path),
  selectFiles: () => ipcRenderer.invoke('select-files'),
  addBookmark: (bookmark) => ipcRenderer.invoke('add-bookmark', bookmark),
  removeBookmark: (id) => ipcRenderer.invoke('remove-bookmark', id),
  openBookmark: (url) => ipcRenderer.invoke('open-bookmark', url),
  addApp: (app) => ipcRenderer.invoke('add-app', app),
  removeApp: (id) => ipcRenderer.invoke('remove-app', id),
  launchApp: (path) => ipcRenderer.invoke('launch-app', path),
  getInstalledApps: () => ipcRenderer.invoke('get-installed-apps'),
  addTask: (task) => ipcRenderer.invoke('add-task', task),
  addTasksBatch: (tasks) => ipcRenderer.invoke('add-tasks-batch', tasks),
  toggleTask: (id) => ipcRenderer.invoke('toggle-task', id),
  deleteTask: (id) => ipcRenderer.invoke('delete-task', id),
  attachToTask: (taskId, attachment) => ipcRenderer.invoke('attach-to-task', { taskId, attachment }),
  detachFromTask: (taskId, attachmentId) => ipcRenderer.invoke('detach-from-task', { taskId, attachmentId }),
  switchMode: (id) => ipcRenderer.invoke('switch-mode', id),
  openModeSelector: () => ipcRenderer.invoke('open-mode-selector'),
  onSetPanel: (callback) => ipcRenderer.on('set-panel', (_, section) => callback(section)),
  onDataUpdated: (callback) => ipcRenderer.on('data-updated', callback)
});